### PR TITLE
CS for the new Media Manger (backend)

### PR DESCRIPTION
**Pull request by zero-24**
Hi @yireo @jissereitsma 

This is a first step of CS for the new media manger (backend). :smile:

I hope i have send it to the correct repo ;)

#### Changes in this PR

- Doc block fixes (mainitly add `@since 3.6`)
- Codestyle
- Adds `desktop.ini` to the `skipfiles array`

### CODE REVIEW

**Comment by jissereitsma** [comment]
Huge PR. Awesome work. This is the right branch. But just now I accepted the other smaller 2 PRs and I think that invalidated this PR. Some of the changes in this PR are solid. I agree disagree with some. For instance, I had a couple of lines where I instantiated the line `$user = JFactory::getUser()` only to use the variable once. Instead, you moved this into the line where the variable was actually needed, without the requirement for a variable. The cost of a variable like this is almost nill, and I like the explicit one better because it allows for placing `@var` doc comments plus regular commens, while the approach without variable does not. Anyway, awesome PR.

Could you update the PR so it matches the current tree, so it merges again?

**Comment by zero-24** [comment]
Ok. I can correct it later today.

If this is the correct branch can you enable that we can open issues? I have installed this branch and expirienced some issues where i have no idea how to fix.
I have also some implementation questions ;)

**Comment by jissereitsma** [comment]
No problem. "Issues" are now enabled.

**Comment by zero-24** [comment]
i have fixed the $user & $date var and fixed the merge conflict

**Comment by jissereitsma** [comment]
Sorry for the late reply. Merging now. I'll be picking up on the remaining project soon. Thanks for the PR!

**Pull request merged**
